services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./db-scripts:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root